### ISSUE TITLE
On Startup error: io.listen is not a function 

### ISSUE THREAD

**Issue by kpayson** [rabchev/web-terminal#28]
web-terminal --port 8088
Web-Terminal running at http://localhost:8088/terminal
/usr/local/lib/node_modules/web-terminal/lib/terminal.js:155
    io = io.listen(server, { log: false });
            ^

TypeError: io.listen is not a function
    at initialize (/usr/local/lib/node_modules/web-terminal/lib/terminal.js:155:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-terminal/bin/run.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by nzfarmer1** [comment]
Following

**Comment by Enzo-21** [comment]
Solved it by adding:

let protocol = "http";
 http = require(protocol);
let server = http.createServer();

in the begining of the terminal.js file

**Comment by ychdesign** [comment]
io = io.listen(server, { log: false });
=> io = io(server, { log: false });

**Comment by tellerincorporated** [comment]
> io = io.listen(server, { log: false }); => io = io(server, { log: false });

please can you explain why this works
